### ISSUE TITLE
502 Bad Gateway: The return

### ISSUE THREAD

**Issue by scith** [Chao-Man/couchpotato_ynh#2]
Hello man :+1:
The "502 Bad Gateway" error returned from one day to the other. I reinstalled the app from scratch, it worked again for a few days and then crashed again.
I tried stopping the service in the interface but it doesn't work. Rebooting the server did not change anything either, I had to reinstall the app (and loose the settings).

Any idea please? Is there any log I could forward?

Thanks

**Comment by Chao-Man** [comment]
Hi there.




Sorry about that, it's probably because the Python virtualenv directory is installed inside of the main couchpotato directory, when couchpotato auto-upgrades, it gets overriden. You may want to disable auto updates on couchpotato, as it doesn't restart the couchpotato service after it finishes the upgrade. I’m working on a fix now, just spinning up yunohost to test it on.


Cheers




On Sunday, Jan 18, 2015 at 10:55 am, Jeff <notifications@github.com>, wrote:

Hello man 
 The "502 Bad Gateway" error returned from one day to the other. I reinstalled the app from scratch, it worked again for a few days and then crashed again.
 I tried stopping the service in the interface but it doesn't work. Rebooting the server did not change anything either, I had to reinstall the app (and loose the settings).
 Any idea please? Is there any log I could forward?
 Thanks

**Comment by Chao-Man** [comment]
Hey scith, I've fixed the issue in the latest commit. However you'll have to remove couchpotato using the yunohost admin panel and reinstall the latest version.

Cheers.
